/*
Practice Questions--
(1) Retrieve the total number of rentals made in the Sakila database.
*/
Select count(*) from rental;

/*
Practice Questions--
(2) Find the average rental duration (in days) of movies rented from the Sakila database.
*/
Select avg(rental_duration) from film;

/*
Practice Questions-- 
(3) Display the first name and last name of customers in uppercase.
*/
Select upper(first_name),upper(last_name) from customer;

/*
Practice Questions-- 
(4) Extract the month from the rental date and display it alongside the rental ID.
*/
Select rental_id, monthname(rental_date) from rental;

/*
Practice Questions-- 
(5)Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
*/
Select customer_id , count(rental_id) from rental group by customer_id;

/*
Practice Questions-- 
(6) Find the total revenue generated by each store.
*/

Select staff_id ,sum(amount) from payment group by staff_id;

/*
Practice Questions-- 
(7) Display the title of the movie, customer s first name, and last name who rented it.
*/


Select title, first_name, last_name from
film inner join inventory on 
film.film_id =inventory.film_id
inner join rental on 
inventory.inventory_id = rental.inventory_id
inner join customer on 
rental.customer_id = Customer.customer_id;

/*
Practice Questions-- 
(8) Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
*/

Select first_name, last_name, title from 
actor inner join film_actor on 
actor.actor_id = film_actor.actor_id
inner join film on 
film_actor.film_id = film.film_id where title = "Gone with the wind";



/*
(1) Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.
*/

Select category_id, count(*) from
film_category inner join film on
Film_category.film_id = film.film_id group by category_id;


/*
(2) Find the average rental rate of movies in each language.
*/

Select Name, avg(rental_rate) from 
film inner join language on 
film.language_id = language.language_id group by name;


/*
(3) Retrieve the customer names along with the total amount they've spent on rentals.
*/

Select first_name, sum(Amount) from 
Customer inner join payment on 
Customer.customer_id = payment.customer_id
inner join rental on
payment.customer_id = rental.customer_id group by First_name;

/*
(4) List the titles of movies rented by each customer in a particular city (e.g., 'London').
*/

Select City, Title from 
City inner join address on 
City.city_id = Address.city_id
inner join customer on 
Address.address_id = customer.address_id
inner join rental on 
Customer.customer_id = Rental.customer_id
inner join inventory on
Rental.inventory_id = inventory.inventory_id
inner join film on 
Inventory.film_id = Film.film_id;

/*
(5) Display the top 5 rented movies along with the number of times they've been rented.
*/

Select title, count(rental_id) from 
film inner join inventory on 
Film.film_id = Inventory.film_id
inner join rental on 
Inventory.Inventory_id = Rental.Inventory_id group by Title limit 5;

/*
(6) Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
*/

Select customer.customer_id, Customer.first_name, customer.last_name from 
customer inner join rental on
customer.customer_id = rental.customer_id
inner join inventory on
rental.inventory_id = inventory.inventory_id where inventory.store_id in(1,2) group by customer.customer_id;



